#!/bin/sh

# post installation script for KORGcart
# Krupczak.org Cartographer Agent
# http://www.krupczak.org/cartographer
#

CART_DIR=$BASEDIR/cartographer

# copy start files to /etc/init.d/

if [ -f $CART_DIR/init.solaris ]; then
   cp -f $CART_DIR/init.solaris /etc/init.d/cartographer
   ln -s /etc/init.d/cartographer /etc/rc3.d/S91cartographer
fi

exit 0

